function getWord(left, right) {
    var str = left+right
	return str[0].toUpperCase() +str.slice(1)
}

console.log(getWord("maga", "zine"), "Magazine")
console.log(getWord("reli", "able"), "Reliable")
console.log(getWord("impl", "icit"), "Implicit")
console.log(getWord("docu", "ment"), "Document")
console.log(getWord("oppo", "site"), "Opposite")
console.log(getWord("offi", "cial"), "Official")
console.log(getWord("disa", "gree"), "Disagree")
console.log(getWord("acci", "dent"), "Accident")
console.log(getWord("omis", "sion"), "Omission")
console.log(getWord("vigo", "rous"), "Vigorous")
console.log(getWord("pred", "ator"), "Predator")
console.log(getWord("prog", "ress"), "Progress")
console.log(getWord("inva", "sion"), "Invasion")
console.log(getWord("fare", "well"), "Farewell")
console.log(getWord("majo", "rity"), "Majority")
console.log(getWord("pers", "onal"), "Personal")
console.log(getWord("sequ", "ence"), "Sequence")
console.log(getWord("gove", "rnor"), "Governor")
console.log(getWord("igno", "rant"), "Ignorant")
console.log(getWord("fini", "shed"), "Finished")